name: Release

on:
  release:
    types: [ published ]

jobs:
  Build_And_Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-w -s"  -o ghproxy .

      - name: Build
        run: |
          mkdir -p build
          env GOOS=windows GOARCH=amd64 go build -o ./build/gget-win.exe .
          env GOOS=linux GOARCH=amd64 go build -o ./build/gget-linux .
          env GOOS=darwin GOARCH=amd64 go build -o ./build/gget-mac .
          ls -alh ./build

      - name: Create Release Win
        uses: JasonEtco/upload-to-release@master
        with:
          args: gget-win.exe application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Linux
        uses: JasonEtco/upload-to-release@master
        with:
          args: gget-linux application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Mac
        uses: JasonEtco/upload-to-release@master
        with:
          args: gget-mac application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
